name: Run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test-ubuntu-netcoreapp3_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore src/GraphQL.sln
    - name: Build solution (debug config)
      run: dotnet build --no-restore src/GraphQL.sln
    - name: Test solution (debug config) using netcoreapp3.1
      run: dotnet test --framework netcoreapp3.1 --no-restore src/GraphQL.sln
      
  test-ubuntu-netcoreapp2_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.x'
    - name: Test GraphQL.Tests.csproj
      run: dotnet test --framework netcoreapp2.1 --no-restore src/GraphQL.Tests/GraphQL.Tests.csproj
    - name: Test GraphQL.DataLoader.Tests.csproj
      run: dotnet test --framework netcoreapp2.1 --no-restore src/GraphQL.DataLoader.Tests/GraphQL.DataLoader.Tests.csproj
      
  test-windows-net48:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore src\GraphQL.sln
    - name: Build all targets
      run: dotnet build --no-restore src\GraphQL.sln
    - name: Test GraphQL.Tests.csproj with net48
      run: dotnet test --framework net48 --no-restore src\GraphQL.Tests\GraphQL.Tests.csproj
    - name: Test GraphQL.DataLoader.Tests.csproj with net48
      run: dotnet test --framework net48 --no-restore src\GraphQL.DataLoader.Tests\GraphQL.DataLoader.Tests.csproj
