name: Run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use .NET Core 2.1 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Use .NET Core 3.1 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Allow both runtimes
        # https://github.com/actions/setup-dotnet/issues/25#issuecomment-646925506
        shell: pwsh
        run: |
          $version = Split-Path (Split-Path $ENV:DOTNET_ROOT -Parent) -Leaf;
          $root = Split-Path (Split-Path $ENV:DOTNET_ROOT -Parent) -Parent;
          $directories = Get-ChildItem $root | Where-Object { $_.Name -ne $version };
          foreach ($dir in $directories) {
            $from = $dir.FullName;
            $to = "$root/$version";
            Write-Host Copying from $from to $to;
            Copy-Item "$from\*" $to -Recurse -Force;
          }
      - name: Install dependencies
        run: dotnet restore src/GraphQL.sln
      - name: Build solution (debug config)
        run: dotnet build --no-restore src/GraphQL.sln -p:NoWarn=CS1591
      - name: Test solution (debug config)
        run: dotnet test --no-restore src/GraphQL.sln
      
  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Use .NET Core 2.1 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Use .NET Core 3.1 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Allow both runtimes
        # https://github.com/actions/setup-dotnet/issues/25#issuecomment-646925506
        shell: pwsh
        run: |
          $version = Split-Path (Split-Path $ENV:DOTNET_ROOT -Parent) -Leaf;
          $root = Split-Path (Split-Path $ENV:DOTNET_ROOT -Parent) -Parent;
          $directories = Get-ChildItem $root | Where-Object { $_.Name -ne $version };
          foreach ($dir in $directories) {
            $from = $dir.FullName;
            $to = "$root/$version";
            Write-Host Copying from $from to $to;
            Copy-Item "$from\*" $to -Recurse -Force;
          }
      - name: Install dependencies
        run: dotnet restore src/GraphQL.sln
      - name: Build solution (debug config)
        run: dotnet build --no-restore src/GraphQL.sln -p:NoWarn=CS1591
      - name: Test solution (debug config)
        run: dotnet test --no-restore src/GraphQL.sln

  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use .NET Core 3.1 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        run: dotnet restore src/GraphQL.sln
      - name: Build solution (release config)
        run: dotnet build --no-restore src/GraphQL.sln -c Release -p:NoWarn=CS1591 -p:VersionSuffix=${ GITHUB_RUN_ID }
      - name: Pack solution (release config)
        run: dotnet pack --no-restore src/GraphQL.sln -c Release -p:VersionSuffix=${ GITHUB_RUN_ID }
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Nuget packages
          path: |
            src/GraphQL/bin/Release/*.nupkg
            src/GraphQL.NewtonsoftJson/bin/Release/*.nupkg
            src/GraphQL.SystemTextJson/bin/Release/*.nupkg
